name: Terraform Validation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

      region:
        description: "Select Region"
        required: true
        type: choice
        options:
          - us-east-2
          - us-east-1
          

permissions:
  id-token: write
  contents: read

jobs:

  validate-Platform-and-Data:
    name: Validate ${{ matrix.stack }}
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}  ## Github environment object created in project repo

    env:
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_region: ${{ inputs.region }}
      TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}

    strategy:
      matrix:
        stack:
          - platform
          - data

    defaults:
      run:
        working-directory: live/${{ inputs.environment }}/${{ matrix.stack }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ inputs.region }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

