name: Terraform Validation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

permissions:
  id-token: write
  contents: read

jobs:

  validate-platform:
    name: Validate Platform
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ inputs.environment }}

    defaults:
      run:
        working-directory: live/${{ inputs.environment }}/platform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate


  validate-data:
    name: Validate Data
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ inputs.environment }}

    defaults:
      run:
        working-directory: live/${{ inputs.environment }}/data

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate